const data = [
  { name: "HTML5", icon: "img/html.png" },
  { name: "CSS3", icon: "img/css.png" },
  { name: "JavaScript", icon: "img/js.png" },
  { name: "TypeScript", icon: "img/typescript.png" },
  { name: "Angular", icon: "img/angular.png" },
  { name: "Node.js", icon: "img/nodeJs.png" },
  { name: "Bootstrap", icon: "img/bootstrap.png" },
  { name: "SASS/SCSS", icon: "img/sass.png" },
  { name: "jQuery", icon: "img/jQuery.png" },
  { name: "Firebase", icon: "img/firebase.png" },
  { name: "Apache Cordova", icon: "img/apacheCordova.png" },
  { name: "Ionic", icon: "img/ionic.png" },
  { name: "Flutter", icon: "img/flutter.png" },
  { name: "MySQL", icon: "img/mySql.png" },
  { name: "MongoDB", icon: "img/mongodb.png" },
  { name: "Git", icon: "img/git.png" },
  { name: "GitHub", icon: "img/github.png" },
  { name: "Python Programming", icon: "img/python.png" },
  { name: "Laravel", icon: "img/Laravel.png" },
  { name: "WordPress", icon: "img/WordPress.png" },
  { name: "Canva", icon: "img/canva.png" },
  { name: "Figma", icon: "img/Figma.png" },
  { name: "Java", icon: "img/java.png" },
  { name: "Swift", icon: "img/swift.png" },
  { name: "C#", icon: "img/CSharp.png" },
  { name: "Adobe Illustrator", icon: "img/adobe.png" }, // Illustrator ka alag icon nahi mila
  { name: "Photoshop", icon: "img/photoshop.png" },
  { name: "Visual Studio Code", icon: "img/vsCode.png" },
  { name: "NumPy", icon: "img/numpy.png" },
  { name: "Google Docs", icon: "img/GoogleDocs.png" },
  { name: "Kubernetes", icon: "img/kubernetes.png" },
  { name: "Docker", icon: "img/docker.png" },
  { name: "Google Sheets", icon: "img/googleSheets.png" },
];

export default data;
